
(require 'color-theme)

(defun color-theme-beauty-black ()
  (interactive)
  (color-theme-install
   '(color-theme-beauty-black
      ((background-color . "#070808")
      (background-mode . light)
      (border-color . "#1a1a1a")
      (cursor-color . "#fce94f")
      (foreground-color . "#eeeeec")
      (mouse-color . "black"))
     (fringe ((t (:background "#1a1a1a"))))
;;     (mode-line ((t (:foreground "#eeeeec" :background "#555753"))))
     (mode-line ((t (:foreground "#14f04d" :background "#555753"))))
     (region ((t (:background "#0d4519"))))
     (font-lock-builtin-face ((t (:bold t :foreground "#f02470" :weight semi-bold))))
     (font-lock-comment-face ((t (:foreground "#888a85"))))
     (font-lock-function-name-face ((t (:foreground "#edd400"))))
     (font-lock-keyword-face ((t (:bold t :foreground "#c572cf" :weight semi-bold))))
     (font-lock-string-face ((t (:foreground "#09afce"))))
     (font-lock-type-face ((t (:foreground"#8ae234"))))
     (font-lock-variable-name-face ((t (:foreground "#eeeeec"))))
     (minibuffer-prompt ((t (:foreground "#729fcf" :bold t))))
     (font-lock-warning-face ((t (:foreground "Red" :bold t))))
     )))

(defun inspiration-630157 ()
  "Theme generated by Sweyla: http://inspiration.sweyla.com/code/seed/630157/"
  (interactive)
  (color-theme-install
   '(inspiration-630157
     ((background-color . "#120000")
      (foreground-color . "#FFFFFF")
      (background-mode . dark)
      (border-color . "#323232")
      (cursor-color . "#FFFFFF")
      (mouse-color . "#323232"))
     (mode-line ((t (:foreground "#FFFFFF" :background "#323232"))))
     (region ((t (:background "#323232"))))

     (font-lock-comment-face ((t (:foreground "#5182CE"))))
     (font-lock-constant-face ((t (:foreground "#15BF25"))))
     (font-lock-builtin-face ((t (:foreground "#394DEF"))))
     (font-lock-function-name-face ((t (:foreground "#1DFFAD"))))
     (font-lock-variable-name-face ((t (:foreground "#FF5FFF"))))
     (font-lock-keyword-face ((t (:foreground "#96FFFF"))))
     (font-lock-string-face ((t (:foreground "#833F99"))))
     (font-lock-doc-string-face ((t (:foreground "#833F99"))))
     (font-lock-type-face ((t (:foreground "#0099A8"))))
     )))

(provide 'hjking-color)
